import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://www.zenga.hu/ingatlan-hirdetes-feladas');
  await page.getByLabel('E-mail cím').click();
  await page.getByLabel('E-mail cím').fill('moraingatlan@gmail.com');
  await page.getByLabel('Jelszó').fill('AQ123edcxsw2');
  await page.getByRole('button', { name: 'Kiválasztás engedélyezése' }).click();
  await page.getByRole('button', { name: 'Belépés' }).click();
  await page.getByRole('button', { name: 'Tovább' }).click();
  await page.getByLabel('Kategória').click();
  await page.getByRole('option', { name: 'Ház', exact: true }).locator('span').first().click();
  await page.getByLabel('Típus').click();
  await page.getByRole('option', { name: 'Családi ház' }).locator('span').first().click();
  await page.getByRole('button', { name: 'Cím' }).click();
  await page.getByRole('button', { name: 'Tovább' }).click();
  await page.getByLabel('Település').click();
  await page.getByLabel('Település').fill('buda');
  await page.getByRole('option', { name: 'Budapest II. kerület' }).locator('div').click();
  await page.getByText('Irányítószám').click();
  await page.getByLabel('Irányítószám').fill('1029');
  await page.getByLabel('Városrész').click();
  await page.getByRole('option', { name: 'Pesthidegkút-Ófalu' }).locator('span').first().click();
  await page.getByText('Utca, házszám', { exact: true }).click();
  await page.getByLabel('Utca, házszám', { exact: true }).fill('Temető 1');
  await page.getByRole('button', { name: 'Tovább' }).click();
  await page.getByLabel('Alapterület').click();
  await page.getByText('Alapterületm²Telekterületm²').click();
  await page.getByText('common.error-flag Alapterület: Ez a mező kötelező').click();
  await page.getByLabel('Alapterület').click();
  await page.getByLabel('Alapterület').fill('1');
  await page.getByLabel('Telekterület').click();
  await page.getByLabel('Telekterület').fill('1');
  await page.getByLabel('Szobák száma', { exact: true }).click();
  await page.getByLabel('Félszobák száma').click();
  await page.getByLabel('Szobák száma', { exact: true }).fill('1');
  await page.getByLabel('Szobák száma', { exact: true }).click();
  await page.getByLabel('Félszobák száma').click();
  await page.getByLabel('Félszobák száma').fill('1');
  await page.getByLabel('Épület szintjeinek száma').click();
  await page.getByLabel('Épület szintjeinek száma').fill('1');
  await page.locator('ib-ui-form-item').filter({ hasText: 'Állapot Válassz' }).getByLabel('').click();
  await page.locator('ib-ui-base-select').filter({ hasText: 'VálasszÚj építésűFelújítottÁ' }).getByRole('combobox').click();
  await page.locator('ib-ui-form-item').filter({ hasText: 'Állapot Válassz Ez a mező kö' }).getByLabel('').click();
  await page.getByText('Új építésű').click();
  await page.locator('ib-ui-form-item').filter({ hasText: 'Fűtés Válassz' }).getByLabel('').click();
  await page.getByRole('option', { name: 'Gáz (héra)' }).getByRole('paragraph').click();
  await page.locator('button').filter({ hasText: 'Nem adta meg a hirdető' }).click();
  await page.getByRole('option', { name: 'A+', exact: true }).locator('span').first().click();
  await page.getByRole('button', { name: 'Tovább' }).click();
  await page.getByRole('option', { name: 'villany' }).click();
  await page.getByRole('option', { name: 'gáz' }).click();
  await page.getByRole('option', { name: 'víz', exact: true }).click();
  await page.getByRole('option', { name: 'csatorna' }).click();
  await page.getByRole('option', { name: 'ipari áram' }).click();
  await page.getByRole('option', { name: 'ipari áram' }).click();
  await page.getByRole('option', { name: 'komfortos', exact: true }).click();
  await page.getByRole('option', { name: 'kocsibeálló' }).click();
  await page.getByRole('option', { name: 'télikert' }).click();
  await page.getByRole('option', { name: 'kamra' }).click();
  await page.getByRole('option', { name: 'am-micro antennás' }).click();
  await page.getByRole('option', { name: 'beépített konyhabútor' }).click();
  await page.getByRole('option', { name: 'vízórás' }).click();
  await page.getByRole('option', { name: 'szigetelt', exact: true }).click();
  await page.getByRole('button', { name: 'Tovább' }).click();
  await page.getByLabel('Cím (opcionális)').click();
  await page.getByLabel('Cím (opcionális)').fill('aaaaaaaaaaa');
  await page.getByLabel('Leírás').click();
  await page.getByLabel('Leírás').fill('aaaaaaaaaaaaaaaaaaaaaaaaa');
  await page.locator('oom-portal-advert-create-edit-step-description div').filter({ hasText: 'Tovább' }).nth(2).click();
  await page.getByRole('button', { name: 'Tovább' }).click();
  await page.getByLabel('Ár', { exact: true }).click();
  await page.getByLabel('Ár', { exact: true }).fill('100 0000');
  await page.getByRole('button', { name: 'Tovább' }).click();
  await page.getByRole('button', { name: 'Tallózz a számítógépedről' }).click();
  await page.getByRole('button', { name: 'Tallózz a számítógépedről' }).setInputFiles('Screenshot 2023-05-12 203314.png');
  await page.getByRole('button', { name: 'Tallózás' }).click();
  await page.getByRole('button', { name: 'Tallózás' }).setInputFiles(['Screenshot 2023-05-12 204750.png', 'Screenshot 2023-05-12 210532.png']);
  await page.getByRole('button', { name: 'Tovább' }).click();
  await page.locator('#radio-label-12 span').first().click();
  await page.getByRole('button', { name: 'Mentés a hirdetés feladása né' }).click();
});